import type { Metadata } from 'next';
import { Raleway, Jost } from 'next/font/google';
import './globals.css';
import classNames from 'classnames';

const raleway = Raleway({
  weight: ['200', '300', '400'],
  subsets: ['latin'],
  variable: '--font-raleway',
});

const jost = Jost({
  weight: ['200', '300', '400'],
  subsets: ['latin'],
  style: ['italic', 'normal'],
  variable: '--font-jost',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={classNames(raleway.variable, jost.variable)}>
        {children}
      </body>
    </html>
  );
}
